branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: lunatrading-env
environment-defaults:
  lunatrading-env:
    branch: null
    repository: null
global:
  application_name: lunatrading
  branch: null
  default_ec2_keyname: LunatradingKey
  default_platform: Python 3.8
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
