# Generated by Django 3.1.7 on 2021-10-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_portfolio_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='AAPL', max_length=250),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='AAPL', max_length=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=5),
        ),
    ]
